title: Naushad Shukoor's Blog
description: > # this means to ignore newlines until "baseurl:"
  Hello World! Welcome to my blog!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Naushad Shukoor # add your name
author-img: naushad_shukoor_square_hd.jpg # add your photo
about-author: DL/NLP/ML enthusiast. I like exploring new technology & algorithms in the field of Data Science for solving real world business problem.
 # add description
social-twitter: naushadshukoor # add your Twitter handle
social-github: naushadS # add your Github handle
social-linkedin: naushad-shukoor # add your Linkedin handle
social-email: naushadshukoor@gmail.com # add your Email address
social-kaggle: naushads


# Disqus
discus-identifier: naushads-github-io # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
